# Generated by Django 5.2.7 on 2025-11-06 01:58

import django.core.validators
import django.db.models.deletion
import tesys_tagboard.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0002_initial_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediatype",
            name="id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="id",
        ),
        migrations.AlterField(
            model_name="media",
            name="dhash",
            field=models.CharField(
                validators=[django.core.validators.RegexValidator("^[0-9a-z]{16}$")]
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(
                unique=True, upload_to=tesys_tagboard.models.unique_filename
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="phash",
            field=models.CharField(
                validators=[django.core.validators.RegexValidator("^[0-9a-z]{16}$")]
            ),
        ),
        migrations.AlterField(
            model_name="mediatype",
            name="template",
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="tesys_tagboard.media",
            ),
        ),
        migrations.AlterField(
            model_name="tagcategory",
            name="prefix",
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_favorite"
            ),
        ),
        migrations.AddConstraint(
            model_name="mediatype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("template__startswith", "image/"),
                    ("template__startswith", "audio/"),
                    ("template__startswith", "video/"),
                    _connector="OR",
                ),
                name="media_valid_mime_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="pool",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_pool_name_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_tag_name_cat"
            ),
        ),
        migrations.AddConstraint(
            model_name="tagalias",
            constraint=models.UniqueConstraint(
                fields=("name", "tag"), name="unique_tagalias_name_tag"
            ),
        ),
    ]
