# Generated by Django 5.2.7 on 2025-11-08 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0003_audio_md5_image_md5_video_md5"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="media_ptr",
        ),
        migrations.RemoveField(
            model_name="image",
            name="media_ptr",
        ),
        migrations.RemoveField(
            model_name="video",
            name="media_ptr",
        ),
        migrations.AddField(
            model_name="audio",
            name="meta",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="tesys_tagboard.media",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="meta",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="tesys_tagboard.media",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="meta",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="tesys_tagboard.media",
            ),
            preserve_default=False,
        ),
    ]
