# Generated by Django 5.2.7 on 2025-11-08 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tesys_tagboard",
            "0004_remove_audio_media_ptr_remove_image_media_ptr_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="meta",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="tesys_tagboard.media",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="meta",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="tesys_tagboard.media",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="meta",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="tesys_tagboard.media",
            ),
        ),
    ]
