# Generated by Django 5.2.7 on 2025-11-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0005_alter_audio_meta_alter_image_meta_alter_video_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="source",
        ),
        migrations.AddField(
            model_name="media",
            name="src_url",
            field=models.URLField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="MediaSource",
        ),
    ]
