# Generated by Django 5.2.7 on 2025-11-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0007_alter_media_src_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagcategory",
            name="category",
            field=models.CharField(
                choices=[
                    ("BA", "basic"),
                    ("AR", "artist"),
                    ("CO", "copyright"),
                    ("RA", "rating"),
                ],
                max_length=2,
            ),
        ),
    ]
