# Generated by Django 5.2.7 on 2025-11-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0008_alter_tagcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.CharField(
                choices=[
                    ("BA", "basic"),
                    ("AR", "artist"),
                    ("CO", "copyright"),
                    ("RA", "rating"),
                ],
                default="BA",
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="TagCategory",
        ),
    ]
