# Generated by Django 5.2.7 on 2025-11-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0010_init_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rating_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Safe"),
                    (1, "Unrated"),
                    (50, "Questionable"),
                    (100, "Explicit"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.CharField(
                choices=[("BA", "basic"), ("AR", "artist"), ("CO", "copyright")],
                default="BA",
                max_length=2,
            ),
        ),
    ]
