# Generated by Django 5.2.7 on 2025-11-15 01:31

import tesys_tagboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0014_alter_tagalias_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="file",
            field=models.FileField(
                unique=True, upload_to=tesys_tagboard.models.media_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                unique=True, upload_to=tesys_tagboard.models.media_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                unique=True, upload_to=tesys_tagboard.models.media_upload_path
            ),
        ),
    ]
