# Generated by Django 5.2.7 on 2025-11-21 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0016_tag_post_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pool",
            new_name="Collection",
        ),
        migrations.RemoveConstraint(
            model_name="collection",
            name="unique_pool_name_user",
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_collection_name_user"
            ),
        ),
    ]
