# Generated by Django 5.2.7 on 2025-11-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0017_rename_pool_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
