# Generated by Django 5.2.7 on 2025-11-27 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0019_post_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edit_date",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="Date and time when the comment was last edited",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post_date",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="Date and time when the comment was posted",
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                db_comment="The foreign key to the Post this comment comments on",
                on_delete=django.db.models.deletion.CASCADE,
                to="tesys_tagboard.post",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                db_comment="The body text of the comment", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                db_comment="The foreign key to the User who posted the comment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
