# Generated by Django 6.0 on 2025-12-10 14:19

import tesys_tagboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0021_image_height_image_thumbnail_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="thumbnail",
            field=models.ImageField(
                height_field="height",
                null=True,
                upload_to=tesys_tagboard.models.media_thumbnail_upload_path,
                width_field="width",
            ),
        ),
    ]
