# Generated by Django 6.0 on 2025-12-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0022_alter_image_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("BA", "basic"), ("AR", "artist"), ("CO", "copyright")],
                default="BA",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="rating_level",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
