# Generated by Django 6.0 on 2025-12-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tesys_tagboard", "0023_alter_tag_category_alter_tag_rating_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["category", "-post_count"]},
        ),
    ]
