# Generated by Django 6.0 on 2026-01-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0025_alter_collection_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locked_comments',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
