# Generated by Django 6.0 on 2026-01-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesys_tagboard', '0026_post_locked_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_date'], 'permissions': [('lock_comments', 'Can lock and unlock the comments of a post')]},
        ),
    ]
